"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { AppShell } from "../app-shell";
import { Badge, EmptyState, Panel } from "../dashboard-ui";
import { api } from "@/lib/api";
type Item = { _id: string; stage: string; updatedAt: string; studentId: { _id: string; fullName: string; email: string } };
export function AssignedStudents() {
  const [items, setItems] = useState<Item[]>([]); const [search, setSearch] = useState(""); const [stage, setStage] = useState(""); const [error, setError] = useState("");
  useEffect(() => { void api<{ applications: Item[] }>("/api/v1/crm/applications?limit=50").then((result) => setItems(result.applications)).catch((reason: Error) => setError(reason.message)); }, []);
  const filtered = useMemo(() => items.filter((item) => (!stage || item.stage === stage) && `${item.studentId.fullName} ${item.studentId.email}`.toLowerCase().includes(search.toLowerCase())), [items, search, stage]);
  return <AppShell role="COUNSELLOR" title="Assigned students" subtitle="Only students currently assigned to you are visible."><Panel title="Student applications"><div className="mb-4 grid gap-3 sm:grid-cols-2"><label className="grid gap-1 text-sm font-semibold">Search<input value={search} onChange={(event) => setSearch(event.target.value)} className="min-h-11 rounded-lg border px-3" placeholder="Name or email" /></label><label className="grid gap-1 text-sm font-semibold">Stage<select value={stage} onChange={(event) => setStage(event.target.value)} className="min-h-11 rounded-lg border px-3"><option value="">All stages</option>{["ENQUIRY","COUNSELLING","DOCUMENTS_PENDING","APPLICATION_SUBMITTED","DECISION_RECEIVED","COMPLETED","CANCELLED"].map((value) => <option key={value}>{value}</option>)}</select></label></div>{error && <p role="alert">{error}</p>}{filtered.length ? <div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead><tr className="border-b text-[var(--muted)]"><th className="p-3">Student</th><th className="p-3">Email</th><th className="p-3">Stage</th><th className="p-3">Updated</th><th className="p-3"><span className="sr-only">Action</span></th></tr></thead><tbody>{filtered.map((item) => <tr key={item._id} className="border-b"><td className="p-3 font-semibold">{item.studentId.fullName}</td><td className="p-3">{item.studentId.email}</td><td className="p-3"><Badge>{item.stage.replaceAll("_", " ")}</Badge></td><td className="p-3">{new Date(item.updatedAt).toLocaleDateString()}</td><td className="p-3"><Link className="font-semibold text-[var(--navy)]" href={`/students/${item.studentId._id}`}>Open student</Link></td></tr>)}</tbody></table></div> : <EmptyState title="No matching students" description="Try changing the search or stage filter." />}</Panel></AppShell>;
}
