"use client";
import { useEffect, useState, type FormEvent } from "react";
import { AppShell } from "../app-shell";
import { Badge, EmptyState, Panel, PrimaryButton } from "../dashboard-ui";
import { api, refreshCsrf } from "@/lib/api";
type ApplicationData = { application: null | { _id: string; stage: string }; history: { _id: string; newStage: string; reason: string; createdAt: string }[] };
type ProfileData = { profile: Record<string, unknown> | null; completion: number };
type Note = { _id: string; content: string; createdAt: string; authorId: { fullName: string } };
const next: Record<string, string | undefined> = { ENQUIRY: "COUNSELLING", COUNSELLING: "DOCUMENTS_PENDING", DOCUMENTS_PENDING: "APPLICATION_SUBMITTED", APPLICATION_SUBMITTED: "DECISION_RECEIVED", DECISION_RECEIVED: "COMPLETED" };
export function StudentDetail({ studentId }: { studentId: string }) {
  const [application, setApplication] = useState<ApplicationData>(); const [profile, setProfile] = useState<ProfileData>(); const [notes, setNotes] = useState<Note[]>([]); const [error, setError] = useState("");
  async function load() { const [a, p, n] = await Promise.all([api<ApplicationData>(`/api/v1/crm/applications/student/${studentId}`), api<ProfileData>(`/api/v1/crm/profiles/${studentId}`), api<{ notes: Note[] }>(`/api/v1/crm/students/${studentId}/notes`)]); setApplication(a); setProfile(p); setNotes(n.notes); }
  useEffect(() => { void Promise.all([api<ApplicationData>(`/api/v1/crm/applications/student/${studentId}`), api<ProfileData>(`/api/v1/crm/profiles/${studentId}`), api<{ notes: Note[] }>(`/api/v1/crm/students/${studentId}/notes`)]).then(([a, p, n]) => { setApplication(a); setProfile(p); setNotes(n.notes); }).catch((reason: Error) => setError(reason.message)); }, [studentId]);
  async function addNote(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); await refreshCsrf(); await api(`/api/v1/crm/students/${studentId}/notes`, { method: "POST", body: JSON.stringify({ content: form.get("content") }) }); event.currentTarget.reset(); await load(); }
  async function transition() { if (!application?.application || !next[application.application.stage]) return; const note = window.prompt("Short transition note"); if (!note) return; await refreshCsrf(); await api(`/api/v1/crm/applications/${application.application._id}/transition`, { method: "POST", body: JSON.stringify({ stage: next[application.application.stage], note }) }); await load(); }
  return <AppShell role="COUNSELLOR" title="Student detail" subtitle="Profile, application progress and internal follow-up in one assigned view.">{error && <p role="alert" className="mb-4 rounded-lg bg-red-50 p-3 text-red-800">{error}</p>}<div className="grid gap-6 lg:grid-cols-2"><Panel title="Academic profile" action={<Badge>{profile?.completion ?? 0}% complete</Badge>}>{profile?.profile ? <dl className="grid grid-cols-2 gap-3 text-sm">{Object.entries(profile.profile).filter(([key]) => !key.startsWith("_") && !["userId","createdAt","updatedAt"].includes(key)).map(([key, value]) => <div key={key}><dt className="text-[var(--muted)]">{key.replace(/([A-Z])/g, " $1")}</dt><dd className="font-semibold">{String(value)}</dd></div>)}</dl> : <EmptyState title="Profile not completed" description="The student has not supplied profile details." />}</Panel><Panel title="Application" action={application?.application ? <Badge>{application.application.stage.replaceAll("_", " ")}</Badge> : undefined}>{application?.application ? <div>{next[application.application.stage] && <PrimaryButton onClick={() => void transition()}>Move to {next[application.application.stage]!.replaceAll("_", " ")}</PrimaryButton>}<ol className="mt-5 space-y-3">{application.history.map((item) => <li key={item._id} className="border-l-2 border-blue-200 pl-3"><p className="font-semibold">{item.newStage.replaceAll("_", " ")}</p><p className="text-sm text-[var(--muted)]">{item.reason}</p></li>)}</ol></div> : <EmptyState title="No application" description="This student has not created an enquiry." />}</Panel><Panel title="Internal counselling notes" className="lg:col-span-2"><form onSubmit={addNote} className="mb-5 grid gap-3"><label className="grid gap-1 text-sm font-semibold">New internal note<textarea name="content" required maxLength={2000} className="min-h-24 rounded-lg border p-3" /></label><PrimaryButton className="justify-self-start">Add note</PrimaryButton></form>{notes.length ? <ul className="space-y-3">{notes.map((note) => <li key={note._id} className="rounded-lg bg-slate-50 p-4"><p className="whitespace-pre-wrap text-sm">{note.content}</p><p className="mt-2 text-xs text-[var(--muted)]">{note.authorId.fullName} · {new Date(note.createdAt).toLocaleString()}</p></li>)}</ul> : <EmptyState title="No internal notes" description="Notes are visible only to assigned staff and administrators." />}</Panel></div></AppShell>;
}
