"use client";
import { useEffect, useState, type FormEvent } from "react";
import { AppShell } from "../app-shell";
import { Badge, EmptyState, Panel, PrimaryButton } from "../dashboard-ui";
import { api, refreshCsrf } from "@/lib/api";
type Task = { _id: string; title: string; description?: string; dueAt: string; priority: "LOW"|"MEDIUM"|"HIGH"; status: string; studentId: { _id: string; fullName: string } };
export function TaskBoard() {
  const [tasks, setTasks] = useState<Task[]>([]); const [status, setStatus] = useState("OPEN"); const [error, setError] = useState("");
  async function load() { setTasks((await api<{ tasks: Task[] }>(`/api/v1/crm/tasks?status=${status}`)).tasks); }
  useEffect(() => { void api<{ tasks: Task[] }>(`/api/v1/crm/tasks?status=${status}`).then((result) => setTasks(result.tasks)).catch((reason: Error) => setError(reason.message)); }, [status]);
  async function complete(id: string) { await refreshCsrf(); await api(`/api/v1/crm/tasks/${id}/complete`, { method: "POST", body: "{}" }); await load(); }
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); await refreshCsrf(); await api("/api/v1/crm/tasks", { method: "POST", body: JSON.stringify({ title: form.get("title"), description: form.get("description") || undefined, studentId: form.get("studentId"), dueAt: form.get("dueAt"), priority: form.get("priority") }) }); event.currentTarget.reset(); await load(); }
  return <AppShell role="COUNSELLOR" title="Follow-up tasks" subtitle="Keep assigned-student follow-up visible and timely."><div className="grid gap-6 xl:grid-cols-[1fr_360px]"><Panel title="My tasks" action={<select value={status} onChange={(event) => setStatus(event.target.value)} className="min-h-10 rounded-lg border px-3" aria-label="Task status"><option>OPEN</option><option>COMPLETED</option><option>CANCELLED</option></select>}>{error && <p role="alert">{error}</p>}{tasks.length ? <ul className="space-y-3">{tasks.map((task) => { const overdue = task.status === "OPEN" && new Date(task.dueAt) < new Date(); return <li key={task._id} className="rounded-xl border p-4"><div className="flex flex-wrap justify-between gap-3"><div><p className="font-bold">{task.title}</p><p className="text-sm text-[var(--muted)]">{task.studentId.fullName} · due {new Date(task.dueAt).toLocaleString()}</p></div><div className="flex gap-2"><Badge tone={overdue ? "danger" : task.priority === "HIGH" ? "warning" : "info"}>{overdue ? "OVERDUE" : task.priority}</Badge>{task.status === "OPEN" && <button className="text-sm font-semibold text-green-700" onClick={() => void complete(task._id)}>Complete</button>}</div></div>{task.description && <p className="mt-3 text-sm">{task.description}</p>}</li>; })}</ul> : <EmptyState title="No tasks in this view" description="Automatic and manual follow-ups will appear here." />}</Panel><Panel title="Create follow-up task"><form onSubmit={create} className="grid gap-4"><label className="grid gap-1 text-sm font-semibold">Title<input name="title" required maxLength={160} className="min-h-11 rounded-lg border px-3" /></label><label className="grid gap-1 text-sm font-semibold">Student ID<input name="studentId" required className="min-h-11 rounded-lg border px-3" /></label><label className="grid gap-1 text-sm font-semibold">Due date<input name="dueAt" required type="datetime-local" className="min-h-11 rounded-lg border px-3" /></label><label className="grid gap-1 text-sm font-semibold">Priority<select name="priority" className="min-h-11 rounded-lg border px-3"><option>LOW</option><option>MEDIUM</option><option>HIGH</option></select></label><label className="grid gap-1 text-sm font-semibold">Description<textarea name="description" maxLength={1000} className="min-h-20 rounded-lg border p-3" /></label><PrimaryButton>Create task</PrimaryButton></form></Panel></div></AppShell>;
}
